// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using example_mvc.Models;

namespace example_mvc.Migrations
{
    [DbContext(typeof(example_mvcContext))]
    [Migration("20190605233845_List")]
    partial class List
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("example_mvc.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Breakfast");

                    b.Property<string>("CreatorId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("Dessert");

                    b.Property<bool>("Dinner");

                    b.Property<bool>("Drink");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PreparationTime")
                        .IsRequired();

                    b.Property<bool>("Preserves");

                    b.Property<bool>("Soup");

                    b.Property<int>("difficulty");

                    b.HasKey("Id");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("example_mvc.Models.RecipeTag", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("TagId");

                    b.Property<int?>("RecipeId");

                    b.Property<int?>("TagId1");

                    b.HasKey("Id", "TagId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("TagId");

                    b.HasIndex("TagId1");

                    b.ToTable("RecipeTag");
                });

            modelBuilder.Entity("example_mvc.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("TagId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("example_mvc.Models.RecipeTag", b =>
                {
                    b.HasOne("example_mvc.Models.Recipe", "Recipe")
                        .WithMany("Tags")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("example_mvc.Models.Recipe")
                        .WithMany("TagList")
                        .HasForeignKey("RecipeId");

                    b.HasOne("example_mvc.Models.Tag", "Tag")
                        .WithMany("Tags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("example_mvc.Models.Tag")
                        .WithMany("TagList")
                        .HasForeignKey("TagId1");
                });
#pragma warning restore 612, 618
        }
    }
}
